disc = ["a","an","the","of","is","was","in","during","got","are","did","took","belongs","to","has","at","on","and"
        ,"or","me","around","celebrated","celebrate","regarding","into","came","existence","exist","rule","legal","become"
    ,"became","does","political","records","any","located","total","how","much","with","my","based","as","being"
    ,"done","found","under","can","you","get","for","offered","offer","by","many","that","have","draw","it","so","draws"
    ,"whome","included","include","through","go","said","happened","whom","whose","who","this","water","body","neft","having"
    ,"what","overall","moving","travelling","travel","go","going","goes","moves"
    ,"if","then","than","be","could","been","weapon","belong"
        ,"shown","hit","come","happen","strike","earthquake","related","relate","relates","relating","called","tell","known"
    , "famous","famously","prize","most","read","both","record","recorded","live","will","goes","stretch","run","over",
      "pass","through","number","numbers","where","from","performed","won","olympics","university","talks","were"]
keys=["(at poles)",
"abbreviation",
"abbreviations",
"absolute magnitude",
"academic staff",
"adjectives",
"admin hq",
"administrative staff",
"admission to union",
"advertising",
"affiliates",
"affiliation",
"affiliations",
"agency executive",
"agency executives",
"agency overview",
"alexa rank",
"annual budget",
"appeared in",
"archipelago",
"area",
"area codes",
"area rank",
"area served",
"armor",
"associate editor",
"at&t u-verse",
"at&t u-verse (u s )",
"athletics",
"australian state",
"availability",
"available in",
"available on many us cable providers",
"available on most cable providers",
"available on most other u s  cable systems",
"available on most u s  and canadian cable systems",
"based in",
"before statehood",
"bell fibe tv (canada)",
"bell fibe tv (canada)sky angel",
"bell tv",
"bell tv (canada)",
"born",
"branding",
"brands",
"broadcast area",
"broadcast programs:",
"budget",
"c-band",
"cable",
"calling code",
"callsign meaning",
"campus",
"capital",
"capital\n(and largest city)",
"capital city",
"carbon",
"categories",
"ceo",
"chairman",
"chancellor",
"child agencies",
"circulation",
"city of boston",
"city of license",
"class",
"cnbc plus",
"cnn com/live",
"colors",
"commercial",
"commissioner",
"company",
"composition",
"comune di aquino",
"constituent country",
"content license",
"continent",
"countries",
"country",
"country of origin",
"county",
"created by",
"crew",
"currency",
"current status",
"default user interface",
"defunct",
"demographics",
"demonym",
"density",
"designed by",
"designer",
"developed from",
"developer",
"developer(s)",
"development status",
"dialing code",
"digital+",
"director of interactive",
"directv",
"directv (u s )",
"dish network",
"dish network (u s )",
"division of:",
"divisions",
"doctoral students",
"drives on the",
"editor",
"editor in chief",
"editor-in-chief",
"elevation",
"elevation change",
"emblems",
"employees",
"endowment",
"engine",
"erp",
"established",
"establishment",
"ethnic groups",
"ethnicity",
"expenses",
"facility id",
"fate",
"federal representation",
"filename extensions",
"fips code",
"first air date",
"first flight",
"first issue",
"fleet size",
"focus",
"footnotes",
"format",
"formation",
"formed",
"former editors",
"former names",
"former type",
"founded",
"founded:",
"founder",
"founder(s)",
"foxnewsgo com",
"foxtel",
"french:",
"frequency",
"genre",
"gnis feature id",
"google fiber",
"google fiber (u s )",
"government",
"governor",
"grouping",
"gvt tv",
"haat",
"habitat",
"head",
"headquarters",
"headquarters location",
"headquarters:",
"height",
"helium",
"highest elevation",
"highest point",
"hiking details",
"historic colonies",
"historic countries",
"hubs",
"hydrogen",
"iata",
"image",
"implementation language",
"in-house (washington)",
"incorporated",
"incorporated (city)",
"independence from great britain",
"industry",
"influenced",
"influenced by",
"initial release",
"internet tld",
"intro",
"iptv",
"ipv6 support",
"irish grid reference",
"iron",
"iso 3166 code",
"issn",
"jurisdiction",
"kernel type",
"key people",
"key people:",
"known for",
"language",
"languages",
"largest city",
"largest metro",
"largest settlement",
"launch date",
"launched",
"leaders",
"legal status",
"legislature",
"length",
"license",
"lieutenant governor",
"location",
"lowest point",
"magnesium",
"main\n-armament",
"main ingredients",
"major implementations",
"managing editors",
"manufacturer",
"marketing target",
"mascot",
"membership",
"metallicity",
"method",
"most recent champion(s)",
"most titles",
"motto",
"motto in english",
"motto(s)",
"mythology",
"national language",
"nationality",
"native client(s) on",
"neon",
"net income",
"newspaper",
"nickname",
"nitrogen",
"no  of locations",
"no  of teams",
"nobel laureates",
"non-metropolitan county",
"number built",
"number of employees",
"number of locations",
"observation data",
"occupation",
"oclc number",
"official language",
"official languages",
"official website",
"ons code",
"operating income",
"operating system",
"operational\nrange",
"opinion editor",
"orbital characteristics",
"original author(s)",
"os",
"os family",
"os grid reference",
"owned by",
"owner",
"owner(s)",
"oxygen",
"paradigm",
"parent",
"parent agency",
"parent organization",
"parent:",
"patron saint",
"photo editor",
"photospheric composition (by mass)",
"physical characteristics",
"picture format",
"place of origin",
"platform",
"platforms",
"political alignment",
"population",
"population\n(end of march 2014)[3]",
"population (1 december 2009)",
"population (2011 est )",
"population (2013)[4][5][6][7][8]",
"postal code",
"postgraduates",
"power/weight",
"preceding agencies",
"preceding agency",
"predecessor",
"president",
"preview release",
"primary",
"primary user",
"produced",
"production history",
"production output",
"products",
"profit",
"province",
"provinces",
"provost",
"publication types",
"publisher",
"radixtv",
"region",
"regions with significant populations",
"registration",
"related ethnic groups",
"religion",
"residence",
"revenue",
"role",
"rotation characteristics",
"saint day",
"satellite",
"satellite radio",
"season",
"secondary",
"secretary of state",
"services",
"settled (town)",
"shaw direct",
"shaw direct (canada)",
"sidereal rotation period\n(at equator)",
"silicon",
"similar creatures",
"sirius",
"sirius (u s )",
"sirius xm (u s )",
"sister channel(s)",
"sister newspapers",
"sister stations",
"size",
"sky",
"sky deutschland",
"sky italia",
"sky tv (new zealand)",
"sling tv",
"slogan",
"slogan or nickname",
"slogan(s)",
"source model",
"sovereign state",
"spanish:",
"species",
"specifications",
"spectral classification",
"speed",
"spoken languages",
"sport",
"sports",
"sports editor",
"stable release",
"staff writers",
"starhub",
"state",
"status",
"streaming media",
"streaming news network",
"student newspaper",
"students",
"sub grouping",
"subsidiaries",
"successor",
"sulfur",
"suspension",
"time zone",
"time zone(s)",
"time zones",
"title",
"total assets",
"total circulation\n(2013)",
"total circulation\n(december 2012)",
"total circulation\n(june 2012)",
"total circulation\n(june 2013)",
"total equity",
"total population",
"traded as",
"trail difficulty",
"trailheads",
"tv partner(s)",
"type",
"type of site",
"typing discipline",
"u s  house delegation",
"u s  senators",
"undergraduates",
"use",
"users",
"variations",
"verizon fios",
"verizon fios (u s )",
"volunteers",
"web address",
"webcast",
"website",
"website:",
"weight",
"width",
"working state",
"written in",
"xfinity",
"xm",
"xm (u s )",
"year founded"]
